---
title: "Discussion Week 4"
author: "Anna Piskun"
date: "1/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/Desktop")
mydata=read.csv("discussion4_data.csv")
mydata
```

1. Fit a linear model predicting y from x and plot the resulting regression line and residual plot. What do you see in the residuals?

```{r}
#1 
model1 <- lm(y~x, data = mydata)
plot(y~x, mydata)
lines(mydata$x, model1$fitted.values, col = "red", lwd = 3)
plot(mydata$x,model1$residuals)
plot(model1)

```

```{r}
#2
model2 <- lm(y~poly(x,2,raw=T),data=mydata)
lm(y~I(x^2)+x,data=mydata)
plot(y~x,mydata)
#lines(mydata$x, model1$fitted.values,col="red",lwd=3)
lines(mydata$x,model2$fitted.values,col="blue",lwd=3)
plot(model2)

plot(mydata$x,model2$residuals)
```

```{r}
#3

model3 <- lm(y~poly(x,3),data=mydata)
#lm(y~I(x^3) +I(x^2)+x,data=mydata)
plot(y~x, mydata)
lines(mydata$x,model1$fitted.values,col="red",lwd=3)
lines(mydata$x,model2$fitted.values,col="green",lwd=3)
lines(mydata$x,model3$fitted.values,col="blue",lwd=3)
plot(model3)
plot(mydata$x,model3$residuals)

```

```{r}
#4 
summary(model1)
summary(model2)
summary(model3)
```
would go with 3rd order because it has the higher Rsquared and fits the data better

```{r}
model10 = lm(y~poly(x,10),data=mydata)
plot(y~x,mydata)
plot(y~x, mydata)
lines(mydata$x,model10$fitted.values,col="black",lwd=3)
lines(mydata$x,model1$fitted.values,col="red",lwd=3)
lines(mydata$x,model2$fitted.values,col="green",lwd=3)
lines(mydata$x, model3$fitted.values,col="blue",lwd=3)
plot(mydata$x,model10$residuals)
summary(model10)
```

```{r}
rsquared <- numeric(10)
for(i in 1:10) {
  rsquared[i] <- summary(lm(y~poly(x,i),data=mydata))$r.squared
}
df <- data.frame(n=1:10, rsquared=rsquared)
plot(rsquared~n, data=df)
#or
plot(1:10, 
     sapply(1:10,
            function(n)
             summary(lm(y~poly(x,n),data=mydata))$r.squared),
     type="b")
sapply(1:10, toString)
#rsquared improves significantly from linear, to quadratic, to cubic --> still improving, but not by that much. Would go with cubic model as our choice, adding more terms improves the fit but does not create a better model.
```

