---
title: "DiscussionStats101A_Week5"
author: "Anna Piskun"
date: "2/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#question 1
set.seed(123)
x=runif(30)
beta0=1
beta1=3

simulation1 <- function()
{
  y=beta0+beta1*x+rnorm(30)
  model=lm(y~x)
  return(model$coefficients[2])
}

output_beta1hat=sapply(1:1000, function(x)
  simulation1())
hist(output_beta1hat)

#true mean = to true parameter because it looks normal, centered around 3

#question 2 

simulation2 <- function()
{
  y=beta0+beta1*x+rt(30,df=1)
  model=lm(y~x)
  return(model$coefficients[2])
}
output_beta2hat=sapply(1:1000, function(x)
  simulation2())
hist(output_beta2hat)
#t distribution has heavier tails than normal distribution leads to more variation in the QQ plot (forces us to question the normality of our residuals). More uncertainty/variance in the values of the slope

simulation3 <- function()
{
  y=beta0+beta1*x+rnorm(30,sd=x^2)
  model=lm(y~x)
  return(model$coefficients[2])
}
output_beta3hat=sapply(1:1000, function(x)
  simulation3())
hist(output_beta3hat)

simulation4 <- function()
{
  y=beta0+rnorm(30)
  model=lm(y~x)
  return(model$coefficients[2])
}
output_beta4hat=sapply(1:1000, function(x)
  simulation4())
hist(output_beta4hat)

#as data increases variance decreases. Prediction interval does not take advantage of decreasing variance as n increase, takes into account is the uncertainty of the residuals (how much variance does everyone with a certain amount of x actually have as opposed to average) - its a conditional distribution. 
```

